var CodeCountries = ['ru', 'at', 'az', 'am', 'by','be','bg','gb','hu','de','gr','ge','il','es','it','kz','cy','kg','lv','lt','lu','md','nl','no','pl','pt','ro','rs','sk','si','tr','uz','ua','fr','hr','cz','ch','se','ee'];
 var CodePhone = ['+7 (XXX)XXX-XX-XX',
                  '+43 XXX-XXX-XXX',
                  '+994 XXX-XXX-XX',
                  '+374 XXX-XXX-XX',
                  '+375 XXX-XXX-XX',
                  '+32 XXX-XXX-XXX',
                  '+359 XXX-XXX-XX',
                  '+44 XXX-XXX-XXX',
                  '+36 XXX-XXX-XXX',
                  '+490 XXX-XXX-XX',
                  '+30 XXX-XXX-XXX',
                  '+995 XXX-XXX-XX',
                  '+972 XXX-XXX-XX',
                  '+34 XXX-XXX-XXX',
                  '+39 XXX-XXX-XXX',
                  '+77 XXX-XXX-XXX',
                  '+357 XXX-XXX-XX',
                  '+996 XXX-XXX-XX',
                  '+371 XXX-XXX-XX',
                  '+370 XXX-XXX-XX',
                  '+352 XXX-XXX-XX',
                  '+373 XXX-XXX-XX',
                  '+31 XXX-XXX-XXX',
                  '+47 XXX-XXX-XXX',
                  '+48 XXX-XXX-XXX',
                  '+351 XXX-XXX-XX',
                  '+40 XXX-XXX-XXX',
                  '+381 XXX-XXX-XX',
                  '+421 XXX-XXX-XX',
                  '+386 XXX-XXX-XX',
                  '+90 XXX-XXX-XXX',
                  '+998 XXX-XXX-XX',
                  '+380 XXX-XXX-XX',
                  '+33 XXX-XXX-XXX',
                  '+385 XXX-XXX-XX',
                  '+420 XXX-XXX-XX',
                  '+41 XXX-XXX-XXX',
                  '+46 XXX-XXX-XXX',
                  '+372 XXX-XXX-XX'];
$('select.country_select').change(function(){
    var ChangedCode = this.options [this.selectedIndex].value;
    var X = CodeCountries.indexOf(ChangedCode);
    $('input#phone').attr('placeholder', CodePhone[X]);
});