(function() {
    'use strict';

    window.countryList = {
        at: {
            name: 'Австрия',
            code: 'at',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +43 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения',
            isDefault: true
        },
        bg: {
            name: 'Болгария',
            code: 'bg',
            price: '1 лев',
            oldPrice: '239лев',
            labelPrice: '',
            phoneHelper: 'Например +359 123456789',
            nameHelper: 'Мария Агова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        hu: {
            name: 'Венгрия',
            code: 'hu',
            price: '1 фор',
            oldPrice: '39900фор',
            labelPrice: '',
            phoneHelper: 'Например +36 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        de: {
            name: 'Германия',
            code: 'de',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +490 123456789',
            nameHelper: 'Ханна Беккер',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        es: {
            name: 'Испания',
            code: 'es',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +34 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        it: {
            name: 'Италия',
            code: 'it',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +39 1234567890',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        cy: {
            name: 'Кипр',
            code: 'cy',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +357 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        lv: {
            name: 'Латвия',
            code: 'lv',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +371 123456789',
            nameHelper: 'Санита Берзиньш',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        lt: {
            name: 'Литва',
            code: 'lt',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +370 123456789',
            nameHelper: 'Лайма Дауканте',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        pl: {
            name: 'Польша',
            code: 'pl',
            price: '1 злот',
            oldPrice: '599злот',
            labelPrice: '',
            phoneHelper: 'Например +48 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        pt: {
            name: 'Португалия',
            code: 'pt',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +351 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        ro: {
            name: 'Румыния',
            code: 'ro',
            price: '1 RON',
            oldPrice: '599RON',
            labelPrice: '',
            phoneHelper: 'Например +40 123456789',
            nameHelper: 'Мария Ионеску',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        sk: {
            name: 'Словакия',
            code: 'sk',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +421 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        si: {
            name: 'Словения',
            code: 'si',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +386 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        hr: {
            name: 'Хорватия',
            code: 'hr',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +385 123456789',
            nameHelper: 'Екатерина Самойлова',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        cz: {
            name: 'Чехия',
            code: 'cz',
            price: '1 крон',
            oldPrice: '3990крон',
            labelPrice: '',
            phoneHelper: 'Например +420 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        ch: {
            name: 'Швейцария',
            code: 'ch',
            price: '1 франк',
            oldPrice: '120фр.',
            labelPrice: '',
            phoneHelper: 'Например +41 123456789',
            nameHelper: 'Анна Мишкина',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        },
        ee: {
            name: 'Эстония',
            code: 'ee',
            price: '1 евро',
            oldPrice: '78евро',
            labelPrice: '',
            phoneHelper: 'Например +372 123456789',
            nameHelper: 'София Йуримаа',
            nameError: 'Имя обязательно для заполнения',
            phoneError: 'Телефон обязателен для заполнения',
            emailError: 'E-mail incorrect',
            emailSuccess: 'Thanks, e-mail sended',
            countryError: 'Страна обязательна для заполнения'
        }
    };
})();